### ISSUE TITLE
Accessing all images in bulk

### ISSUE THREAD

**Issue by MichaelDoron** [NationalLibraryofIsrael/API#4]
Is there a way to access the images in bulk, and not only one at a time? 
Our group's project depends on a model we train on a large set of pictures, and accessing them one after the other will be time consuming, possibly beyond the time scope of the hackathon

**Comment by NLI-API** [comment]
You can access the resources you need via a IIIF collection (essentially a raw list of the online resources in each of the collections that are part of the Hackathon) - [ROOT of collections](http://iiif.nli.org.il/collections/root.json) (choose the collection you know you're working on).

If you know which collection you're working on that should help you to reach the resources easily.

**Comment by MichaelDoron** [comment]
Thanks for the fast reply!

You wrote on the facebook page not to harvest the API, but is downloading the images automatically through these manifest pages allowed (e.g. via http://iiif.nli.org.il/IIIFv21/FL4378734/full/max/0/default.jpg)?

**Comment by NLI-API** [comment]
We ask users not to systematically download everything, our APIs are not designed for everybody downloading everything all the time, they are designed to on-demand access of needed resources.

If you have one project that needs a set of particular images from a particular collection or two, it's fine that you will access them, since this is not called systematically downloading all the collections.

If you want to pre-cache the images because that's your project needs- that's fine. However, it is best to always retain the linkage with the online resource. You can develop a simple "feeder" that feeds the images into a local web-service that cache them, and then your algorithm make a local WS call for a pre-cached image, which will work faster (for example).

Bear in mind that the URL you provided does not yield the max image resolution.
A quick call to the [Image Information Service](http://iiif.nli.org.il/IIIFv21/FL4378734/info.json) indicates that this image is 534x800 pixels, while the call yields 384x576 (all calls are always limited to 576 pixels for server and network performance reasons).
You need to ask the image by tiles: [Tile 1](http://iiif.nli.org.il/IIIFv21/FL4378734/pct:0,0,50,50/256,/0/default.jpg), [Tile 2](http://iiif.nli.org.il/IIIFv21/FL4378734/pct:0,0,50,50/256,/0/default.jpg) etc..
You don't need to "invent the wheel", there are plenty of libraries around the web that handle IIIF Image API syntax.
